# Generated by Django 4.2.16 on 2024-11-20 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_customuser_email_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='data_atualizacao',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='urgency',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('nao_concluido', 'Não Concluído')], default='aberto', max_length=20),
        ),
    ]
