# Generated by Django 5.2.4 on 2025-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('tecnico', 'Técnico')], default='usuario', max_length=10),
        ),
    ]
